updated deploy yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,99 +1,70 @@
-name: Deployment Workflow
+name: Terraform Deployment
 
 on:
-  push:
-    branches:
-      - staging
-      - production
   workflow_dispatch:
     inputs:
       environment:
-        type: choice
-        description: 'Un-Deploy Deployment Environment'
+        description: "Specify the environment (staging or production)"
         required: true
-        options:
-          - un-deploy-staging
-          - un-deploy-production
-
-env:
-  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+        default: "staging"
+        type: string
+      action:
+        description: "Specify the action (deploy or un-deploy)"
+        required: true
+        default: "deploy"
+        type: string
+  push:
+    branches:
+      - production
+      - staging
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        environment:
-          - staging
-          - production
+    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production' || github.event.inputs.action == 'deploy'
+    permissions:
+      id-token: write
+      contents: read
+
+    concurrency:
+      group: ${{ github.ref_name }}
+      cancel-in-progress: false
+
     steps:
       - name: Checkout code
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-
-      - name: Cache Docker layers
-        uses: actions/cache@v2
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v3
         with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-
+          role-to-assume: arn:aws:iam::317822790556:role/pipelines-cd-github
+          aws-region: us-east-1
 
-      - name: Install dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y python3-pip
-          pip install awscli
-          wget https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
-          unzip terraform_1.5.5_linux_amd64.zip -d /tmp
-          sudo chmod 775 /tmp/terraform
-          sudo mv /tmp/terraform /usr/bin/
-
-      - name: Deploy to Staging
-        if: ${{ matrix.environment == 'staging' }}
-        run: ENVIRONMENT=staging API_DOMAIN=open-ai-staging.mediasix.com API_ROOT_DOMAIN=mediasix.com ./deploy.sh
-
-      - name: Deploy to Production
-        if: ${{ matrix.environment == 'production' }}
-        run: ENVIRONMENT=prod API_DOMAIN=open-ai.mediasix.com API_ROOT_DOMAIN=mediasix.com ./deploy.sh
-
-  un-deploy:
-    runs-on: ubuntu-latest
-    needs: deploy
-    if: github.event_name == 'workflow_dispatch'
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-
-      - name: Cache Docker layers
-        uses: actions/cache@v2
+      - name: Install Terraform
+        uses: hashicorp/setup-terraform@v2
         with:
-          path: /tmp/.buildx-cache
-          key: ${{ runner.os }}-buildx-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-
+          terraform_version: 1.10.3
 
-      - name: Install dependencies
+      - name: Docker Setup Buildx
+        uses: docker/setup-buildx-action@v2.0.0
+
+      - name: Deploy or Un-deploy
         run: |
-          sudo apt-get update
-          sudo apt-get install -y python3-pip
-          pip install awscli
-          wget https://releases.hashicorp.com/terraform/1.5.5/terraform_1.5.5_linux_amd64.zip
-          unzip terraform_1.5.5_linux_amd64.zip -d /tmp
-          sudo chmod 775 /tmp/terraform
-          sudo mv /tmp/terraform /usr/bin/
-
-      - name: Un-deploy Staging
-        if: github.event.inputs.environment == 'un-deploy-staging'
-        run: ENVIRONMENT=staging API_DOMAIN=open-ai-staging.mediasix.com API_ROOT_DOMAIN=mediasix.com ./deploy.sh -d
-
-      - name: Un-deploy Production
-        if: github.event.inputs.environment == 'un-deploy-production'
-        run: ENVIRONMENT=prod API_DOMAIN=open-ai.mediasix.com API_ROOT_DOMAIN=mediasix.com ./deploy.sh -d
+          chmod +x ./deploy.sh
+          chmod +x ./_run_terraform.sh
+          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
+            if [[ "${{ github.event.inputs.action }}" == "un-deploy" ]]; then
+              ENVIRONMENT=staging bash ./deploy.sh -d
+            else
+              ENVIRONMENT=staging bash ./deploy.sh
+            fi
+          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
+            if [[ "${{ github.event.inputs.action }}" == "un-deploy" ]]; then
+              ENVIRONMENT=prod bash ./deploy.sh -d
+            else
+              ENVIRONMENT=prod bash ./deploy.sh
+            fi
+          else
+            echo "Invalid branch for deployment: ${{ github.ref }}"
+            exit 1
+          fi
